### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by heileino** [googol/drinkkiarkisto#1]
Repo/nettisivut ladattu su 15.11.2015 klo 16.10
- Aloitussivu on saatu tässä kehitysvaiheessa yksinkertaisen selkeäksi ja informatiiviseksi. Kyseistä tapaa voisi käyttää myös lopullisessa versiossa, jolloin etusivulla voisi olla muutama jollain kriteereillä valittuja esimerkkidrinkkejä tietoineen. Kriteereitä voisivat olla esimerkiksi haetuimmat drinkit, sesonkiin sopivat drinkit, ylläpidon suositukset jne.
- Olemassa olevat sivunäkymät vaikuttavat toistaiseksi staattisilta, eli niiden tiedoilla ei ole vielä yhteyttä tietokantaan. Uuden drinkin luomissivun näkymässä tarjotaan käyttäjäystävällinen tapa käyttää nuolia oikean annosmäärän lisäämiseksi. Näin käyttäjä saa kätevästi pelkän hiiren avulla syötettyä runsaasti lukuja. Samalla kirjoitusvirheiden mahdollisuutta pienennetään. Drinkkien muokkaussivut toimivat samalla periaatteella ja tarjoavat oikeaoppisesti jo olemassa olevat tiedot muokkauksen tueksi. Näkymät tarjoavat hyvän pohjan varsinaisen sivuston luomiseen.
- Koodin osalta sovelluksen kontrolleri ja näkymät on toteutettu itselleni vieraalla kielellä, JavaScriptillä, joten syvällistä analyysia koodin tasosta on mahdoton antaa.  Päällisin puolin kontrolleri näyttää toteuttavan tehtävänsä drinkkeihin liittyvissä pyynnöissä ohjeistuksessa vaaditulla tavalla. Näkymissä oleva tiedosto server.js näyttää vastaavan routes.php-tiedostoa. Reititykset vaikuttavat valideilta. Muilta osin ymmärrykseni ei riitä näkymien analysointiin, sillä niistä ei löydy tuttuja html-tiedostoja, vaan näkymät on nähtävästi toteutettu jollakin tapaa JavaScript-tiedostojen kautta.
- Tietokantojen tietosisältö on toteutettu mielekkäästi, relaatiotietokantakaaviota mukaillen. Tietokohteiden attribuutteja on riittävästi tarjoamaan haluttuja tietoja tietokohteistaan. Create-table, drop-Table ja add-test-data tiedostot toteutettu toimivalla ja selkeällä tavalla.
- Yhteenvetona voi sanoa, että työ on siinä vaiheessa, että paljon on vielä tehtävää ja työn onnistumisen arviointi ei projektin tässä vaiheessa ole mielekästä. README-tiedosto sisältää hienon selvityksen repositoryn kansiorakenteesta ja sen sisällöstä, mikä auttaa myös asiasta ymmärtämätöntä hieman hahmoittamaan työn rakenteen ideaa. Edellä mainitusta tiedostosta puuttuu kuitenkin ohjeistuksessa vaaditut suorat linkit erilaisiin olemassa oleviin sivunäkymiin. Aihekuvauksessa on monenlaisia vaatimuksia, joita ei ole vielä hahmoteltu ainakaan sellaisissa sivunäkymissä, joihin sivuston etusivulta on pääsy. Olemassa oleva pohja vaikuttaa hyvin ammattimaisesti rakennetulta ja tekijä selvästi tietää katselmoijaa paremmin, mitä on tekemässä ja miten hyviä tietokantasovelluksia luodaan.

**Comment by googol** [comment]
Kiitti katselmoinnista!

Mistä tiedostoista pitäis olla linkit sivunäkymiin? Mulla on menny ohi ohjeistuksessa semmoset (oon aika minimaalisesti sitä lukenukki).

Tosiaan onkin unohtunu tuolta näkymistä joitakin ominaisuuksia, niinkuin ylimääräiset nimet ja drinkkityyppi, vaikka ne tietokantatasolla ovatkin. Pitänee lisätä ne tässä pian ettei unohdu kokonaan. 

Data tulee muuten livenää kannasta :) Se editti-sivu ei tosin osaa tallentaa vielä, ja uuden lisäämisessä validointi on silleen typerä ettei vielä ilmoita virheistä vaan menee takasi siihen formiin ilmottamatta mitään.

**Comment by heileino** [comment]
http://tsoha.github.io/#/johdanto#top. Tuolla PHP-materiaalisivuilla lukee ainakin viikon 2 palautusvaatimuksien kohdalla näin:
"Suunnittele käyttöliittymäsi ja toteuta niistä staattiset HTML-sivut. Muista lisätä linkit toteuttamiisi sivuihin reposi README.md-tiedostoon. (1,5p)
- Suunnittele etusivu
- Suunnittele listaussivut
- Suunnittele muokkaus- ja esittelysivut"

Tärkeää arvostelun kannalta varmasti erityisesti silloin, jos kaikki sivunäkymähahmotelmat eivät ole vielä navigoitavissa etusivun kautta.

**Comment by googol** [comment]
Aivan joo, menny ihan ohi multa toi ku listasin vaatimuksia :D
